package il.ac.hit.project.model;

import java.util.Set;
import il.ac.hit.project.model.entity.Priority;

/**
 * Immutable task value object (Java record) that implements {@link ITask}.
 * Holds: id, title, description, state, and priority.
 * Used across DAO mapping and UI. Because it is immutable, updates are done
 * by creating a new instance
 * equals/hashCode/toString are generated by the record.
 */

public record TaskRecord(
        int id,
        String title,
        String description,
        TaskState state,
        Priority priority
) implements ITask {

    @Override public int getId() { return id; }
    @Override public String getTitle() { return title; }
    @Override public String getDescription() { return description; }
    @Override public TaskState getState() { return state; }

    //Allowed next states from the current state.
    public Set<TaskState> allowedNextStates() { return state.nextStates(); }

    /**
     * Returns a new task with the given next state.
     * If the transition is not allowed, throws {@link IllegalStateException}.
     * Other fields (id, title, description, priority) are copied as-is.
     * @param next the desired next state
     * @return a new {@code TaskRecord} with {@code state = next}
     * @throws IllegalStateException if {@code state → next} is not allowed
     */
    public TaskRecord withState(TaskState next) {
        if (!state.canTransitionTo(next))
            throw new IllegalStateException(state + " → " + next + " not allowed");
        return new TaskRecord(id, title, description, next, priority);
    }

}
